name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          make deps

      - name: Run pre-commit checks (excluding tests)
        run: |
          pip install pre-commit
          SKIP=pytest pre-commit run --all-files

      - name: Run tests
        run: |
          make test

      - name: Build site
        run: |
          make update
