name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies
        run: |
          make deps

      - name: Run pre-commit checks (excluding tests)
        run: |
          SKIP=pytest uv run pre-commit run --all-files

      - name: Run tests
        run: |
          make test

      - name: Build site
        run: |
          make update
